[package]
name = "taksi-tilikirja"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
eframe = "0.28.1"
egui = "0.28.1"
egui_extras = { version = "0.28.1", features = ["chrono"] }
printpdf = "0.7.0"
rusqlite = "0.32.0"
